language: python

python:
- 3.6

services:
- mysql

branches:
  only:
  - develop

env:
  - DJANGO_VERSION=1.11.2

services:
  - mysql

addons:
  apt_packages:
     - libcups2-dev

install:
  - pip3 install --upgrade pip setuptools
  - pip3 install -q Django==$DJANGO_VERSION
  - pip3 install flake8
  - pip3 install coveralls
  - pip3 install mysqlclient
  - pip3 install -q -r requirements.txt

before_script:
  - flake8 edc_registration
  - mysql -e 'create database edc character set utf8;'

script: 
  - coverage run --source=edc_registration manage.py test

after_success:
  - coveralls
