REGISTRATION_STATUS = (
    ('SCREENING', 'SCREENING'),
    ('REGISTERED', 'REGISTERED'),
    ('RANDOMIZED', 'RANDOMIZED'),
    ('OFF_STUDY', 'OFF STUDY'),
)

SUBJECT_TYPE = (
    ('ADULT', 'ADULT'),
    ('MOTHER', 'MOTHER'),
    ('INFANT', 'INFANT'),
    ('SUBJECT', 'SUBJECT'),
    ('INDEX', 'INDEX'),
    ('PARTNER', 'PARTNER'),
)
