# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregisteredsubject',
            name='hostname_created',
            field=models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='registeredsubject',
            name='hostname_created',
            field=models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
