# Generated by Django 2.0.1 on 2018-01-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_registration', '0010_registeredsubject_consent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsubject',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
    ]
